---
version: "3.9"

services:
  vault-server:
    image: vault:latest
    container_name: vault-server
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID
      - VAULT_ADDR="http://0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    