version: "3.9"

services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD
      - APPLICATION_DB
      - APPLICATION_DB_USER
      - APPLICATION_DB_PASSWORD
      - ACCEPT_EULA="Y"
    volumes:
      - ./scripts:/usr/config/scripts