---
version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    networks:
       kafka:
          aliases:
            - zookeeper.local
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: ERROR
      ZOOKEEPER_LOG4J_LOGLEVEL: ERROR
    ports:
      - "2181:2181"
    tmpfs: "/datalog"  
    
  broker:
    image: confluentinc/cp-kafka:latest
    container_name: broker
    networks:
       kafka:
          aliases:
            - broker.local
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR
      KAFKA_LOG4J_LOGLEVEL: ERROR
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper.local:2181
      KAFKA_ADVERTISED_LISTENERS: SSL://localhost:9092
      KAFKA_LISTENERS: SSL://:9092
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.broker.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: broker_keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: broker_sslkey_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.broker.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: broker_truststore_creds
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: " "
      KAFKA_LISTENER_NAME_INTERNAL_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: " "
      KAFKA_SSL_CLIENT_AUTH: required # change to 'requested' to be able to authenticate with just root crt
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SSL_TRUSTSTORE_TYPE: JKS
      KAFKA_SSL_KEYSTORE_TYPE: JKS
    volumes:
      - ./kafka-secrets/secrets:/etc/kafka/secrets
      - ./kafka-secrets/config:/etc/kafka/config

networks:
  kafka:
